<?php
session_start();

if (!isset($_SESSION['username'])) {
    header("Location: login.php");
    exit();
}

require('fpdf/fpdf.php');

$conn = mysqli_connect("localhost", "root", "", "matrimosys");

if (!$conn) {
    die("Connection failed: " . mysqli_connect_error());
}

$report_type = isset($_POST['report_type']) ? $_POST['report_type'] : 'all';
$format = isset($_POST['format']) ? $_POST['format'] : 'csv';

// Prepare query based on report type
switch ($report_type) {
    case 'gender':
        $query = "SELECT username, email, dob, gender FROM profiles WHERE gender IS NOT NULL ORDER BY gender";
        $headers = array('Username', 'Email', 'Date of Birth', 'Gender');
        $title = "Users by Gender Report";
        break;
    case 'age':
        $query = "SELECT username, email, dob, age FROM profiles ORDER BY age";
        $headers = array('Username', 'Email', 'Date of Birth', 'Age');
        $title = "Users by Age Report";
        break;
    case 'location':
        $query = "SELECT username, email, dob, nativity FROM profiles WHERE nativity IS NOT NULL ORDER BY nativity";
        $headers = array('Username', 'Email', 'Date of Birth', 'Location');
        $title = "Users by Location Report";
        break;
    case 'religion':
        $query = "SELECT p.username, p.email, p.dob, r.religion 
                 FROM profiles p 
                 LEFT JOIN tbl_caste c ON p.caste_id = c.caste_id 
                 LEFT JOIN tbl_religion r ON c.religion_id = r.religion_id 
                 ORDER BY r.religion";
        $headers = array('Username', 'Email', 'Date of Birth', 'Religion');
        $title = "Users by Religion Report";
        break;
    case 'education':
        $query = "SELECT p.username, p.email, p.dob, e.education, s.eduSub 
                 FROM profiles p 
                 LEFT JOIN tbl_subEducation s ON p.edusub_id = s.edusub_id 
                 LEFT JOIN tbl_education e ON s.education_id = e.education_id 
                 ORDER BY e.education, s.eduSub";
        $headers = array('Username', 'Email', 'Date of Birth', 'Education', 'Specialization');
        $title = "Users by Education Report";
        break;
    default: // 'all'
        $query = "SELECT username, email, dob FROM profiles ORDER BY username";
        $headers = array('Username', 'Email', 'Date of Birth');
        $title = "All Users Report";
        break;
}

$result = mysqli_query($conn, $query);

// Generate filename
$filename = strtolower(str_replace(' ', '_', $title)) . '_' . date('Y-m-d');

if ($format == 'csv') {
    // CSV Generation
    header('Content-Type: text/csv');
    header('Content-Disposition: attachment; filename="' . $filename . '.csv"');
    
    $output = fopen('php://output', 'w');
    
    // Output headers
    fputcsv($output, $headers);
    
    // Output data rows
    while ($row = mysqli_fetch_assoc($result)) {
        fputcsv($output, $row);
    }
    
    fclose($output);
} elseif ($format == 'pdf') {
    // PDF Generation using FPDF
    $pdf = new FPDF();
    $pdf->AddPage();
    $pdf->SetFont('Arial', 'B', 16);
    
    // Title
    $pdf->Cell(0, 10, $title, 0, 1, 'C');
    $pdf->Ln(5);
    
    // Info lines
    $pdf->SetFont('Arial', '', 10);
    $pdf->Cell(0, 5, 'Generated on: ' . date('F d, Y h:i A'), 0, 1);
    $pdf->Cell(0, 5, 'Generated by: ' . $_SESSION['username'], 0, 1);
    $pdf->Ln(5);
    
    // Table headers
    $pdf->SetFont('Arial', 'B', 11);
    foreach ($headers as $header) {
        $pdf->Cell(40, 7, $header, 1);
    }
    $pdf->Ln();
    
    // Table data
    $pdf->SetFont('Arial', '', 10);
    mysqli_data_seek($result, 0);
    while ($row = mysqli_fetch_assoc($result)) {
        foreach ($row as $value) {
            $pdf->Cell(40, 6, $value, 1);
        }
        $pdf->Ln();
    }
    
    $pdf->Output('D', $filename . '.pdf');
} else {
    die("Unsupported format. Please choose CSV or PDF.");
}

mysqli_close($conn);
exit(); 